baseurl = "/"
languageCode = "en-us"
title = "Turning Point"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Turning Point"
  cover = "images/church.jpg"
  author = "Val√®re JEANTET"
  authorlocation = "Washington,D.C."
  authorwebsite = "http://placeholder.com"
  bio= "Turning Point"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = ""
  twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
